export const FORM_CHANGE = 'FORM_CHANGE'
export const FORM_CLEAR = 'FORM_CLEAR'
export const FORM_BATCH_CHANGE = 'FORM_BATCH_CHANGE'
export const FORM_SET_EDITING_SLUG = 'FORM_SET_EDITING_SLUG'

export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'
export const USER_UPDATE_FAVORITES = 'USER_UPDATE_FAVORITES'
export const USER_UPDATE_DUBS = 'USER_UPDATE_DUBS'

export const DUBTITLE_SET_MEDIA = 'DUBTITLE_SET_MEDIA'

export const ENTITIES_DISCOVER_RECEIVED = 'ENTITIES_DISCOVER_RECEIVED'
