export const FORM_CHANGE = 'FORM_CHANGE'
export const FORM_CLEAR = 'FORM_CLEAR'
export const FORM_BATCH_CHANGE = 'FORM_BATCH_CHANGE'
export const FORM_SET_EDITING_SLUG = 'FORM_SET_EDITING_SLUG'

export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'
